name: conectadas_app
description: "Projeto Elas Conectadas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  adaptive_theme: ^3.5.0
  uuid: ^4.4.2
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.8
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  image: ^4.2.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  extended_text: ^5.0.0
  go_router: ^14.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  #image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    #images/

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
